#!/usr/bin/env python3
"""Regenerate docs/reference/commands.md and docs/reference/mcp.md from the code (always accurate).

    python3 scripts/gen_reference.py
"""
import os
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
os.environ.setdefault("PYTERMWM_RUNTIME_DIR", tempfile.mkdtemp())
os.environ.setdefault("PYTERMWM_STATE_DIR", tempfile.mkdtemp())

from tests.helpers import make_wm  # noqa: E402
from pytermwm.mcp import TOOLS  # noqa: E402


def main():
    wm = make_wm(100, 30)
    for plug in ("effects", "btop", "docker", "mqtt", "ssh", "openai"):
        try:
            wm.ensure_plugins().load(plug)
        except Exception as e:                      # a plugin that cannot load is simply left out
            print("skipping plugin", plug, e, file=sys.stderr)
    cmds = [c for c in wm.commands.commands.values() if not c.hidden]
    by_cat = {}
    for c in sorted(cmds, key=lambda c: c.name):
        by_cat.setdefault(c.category or "other", []).append(c)
    out = ["# Command reference", "",
           "Generated by `scripts/gen_reference.py` (with all bundled plugins loaded). The same list is available as "
           "`pytermwm ctl commands`, `GET /api/commands`, the MCP tool `list_commands` and `help commands` inside the WM.", ""]
    for cat in sorted(by_cat):
        out += ["## " + cat, "", "| command | usage | description |", "|---|---|---|"]
        for c in by_cat[cat]:
            al = (" (alias: %s)" % ", ".join(c.aliases)) if c.aliases else ""
            out.append("| `%s` | `%s` | %s%s |" % (c.name, c.usage.replace("|", "\\|"), (c.help or "").replace("|", "\\|"), al))
        out.append("")
    with open(os.path.join(ROOT, "docs", "reference", "commands.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    mc = ["# MCP tools", "", "Generated by `scripts/gen_reference.py`.", "", "| tool | arguments | description |", "|---|---|---|"]
    for t in TOOLS:
        props = t["inputSchema"].get("properties", {})
        req = set(t["inputSchema"].get("required", []))
        args = ", ".join(("**%s**" if k in req else "%s") % k for k in props) or "-"
        mc.append("| `%s` | %s | %s |" % (t["name"], args, t["description"].replace("|", "\\|")))
    mc += ["", "Bold arguments are required."]
    with open(os.path.join(ROOT, "docs", "reference", "mcp.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(mc) + "\n")
    print("wrote docs/reference/commands.md (%d commands) and mcp.md (%d tools)" % (len(cmds), len(TOOLS)))


if __name__ == "__main__":
    main()
